// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3925.Bot2015;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.smartdashboard.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    public static SpeedController driveTrainrightRear;
    public static SpeedController driveTrainrightFront;
    public static SpeedController driveTrainleftFront;
    public static DoubleSolenoid driveTraindriveShiftSolenoid;
    public static Encoder driveTrainleftDriveEncoder;
    public static Encoder driveTrainrightDriveEncoder;
    public static SpeedController driveTrainleftRear;
    
    public static Encoder elevatorelevatorEncoder;
    public static SpeedController elevatorelevatorMotor;
    public static PIDController elevatorelevatorPIDController;
    
    public static Compressor generalPneumaticscompressor;
    public static SpeedController forkLiftforkliftLiftMotor;
    public static Encoder forkLiftforkliftLiftEncoder;
    public static PIDController forkLiftforkliftPIDController;
    public static Relay intakeleftIntakeMotorRelay;
    public static Relay intakerightIntakeMotorRelay;
    public static DigitalInput intaketoteCapturedSwitch;
    public static Relay intakebottomIntakeMotorRelay;
    public static Solenoid latcheslatchReleaseSolenoid;


    public static void init() {
        driveTrainrightRear = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "rightRear", (Talon) driveTrainrightRear);
        
        driveTrainrightFront = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "rightFront", (Talon) driveTrainrightFront);
        
        driveTrainleftFront = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "leftFront", (Talon) driveTrainleftFront);
        
        driveTrainleftRear = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "leftRear", (Talon) driveTrainleftRear);

        driveTraindriveShiftSolenoid = new DoubleSolenoid(1, 0, 1);      
        LiveWindow.addActuator("DriveTrain", "driveShiftSolenoid", driveTraindriveShiftSolenoid);
        
        driveTrainleftDriveEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "leftDriveEncoder", driveTrainleftDriveEncoder);
        driveTrainleftDriveEncoder.setDistancePerPulse(0.09817477);
        driveTrainleftDriveEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        
        driveTrainrightDriveEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "rightDriveEncoder", driveTrainrightDriveEncoder);
        driveTrainrightDriveEncoder.setDistancePerPulse(0.09817477);
        driveTrainrightDriveEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        
        elevatorelevatorEncoder = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("Elevator", "elevatorEncoder", elevatorelevatorEncoder);
        elevatorelevatorEncoder.setDistancePerPulse(1.0);
        elevatorelevatorEncoder.setPIDSourceParameter(PIDSourceParameter.kDistance);
        elevatorelevatorMotor = new Talon(4);
        LiveWindow.addActuator("Elevator", "elevatorMotor", (Talon) elevatorelevatorMotor);
        
        elevatorelevatorPIDController = new PIDController(1.0, 0.0, 0.0, 0.0, elevatorelevatorEncoder, elevatorelevatorMotor, 0.02);
        LiveWindow.addActuator("Elevator", "elevatorPIDController", elevatorelevatorPIDController);
        elevatorelevatorPIDController.setContinuous(false); elevatorelevatorPIDController.setAbsoluteTolerance(0.2); 
        elevatorelevatorPIDController.setOutputRange(-1.0, 1.0);        

        generalPneumaticscompressor = new Compressor(1);
        
        
        forkLiftforkliftLiftMotor = new Talon(5);
        LiveWindow.addActuator("ForkLift", "forkliftLiftMotor", (Talon) forkLiftforkliftLiftMotor);
        
        forkLiftforkliftLiftEncoder = new Encoder(6, 7, false, EncodingType.k4X);
        LiveWindow.addSensor("ForkLift", "forkliftLiftEncoder", forkLiftforkliftLiftEncoder);
        forkLiftforkliftLiftEncoder.setDistancePerPulse(1.0);
        forkLiftforkliftLiftEncoder.setPIDSourceParameter(PIDSourceParameter.kDistance);
        forkLiftforkliftPIDController = new PIDController(1.0, 0.0, 0.0, 0.0, forkLiftforkliftLiftEncoder, forkLiftforkliftLiftMotor, 0.02);
        LiveWindow.addActuator("ForkLift", "forkliftPIDController", forkLiftforkliftPIDController);
        forkLiftforkliftPIDController.setContinuous(false); forkLiftforkliftPIDController.setAbsoluteTolerance(0.2); 
        forkLiftforkliftPIDController.setOutputRange(-1.0, 1.0);        

        intakeleftIntakeMotorRelay = new Relay(0);
        LiveWindow.addActuator("Intake", "leftIntakeMotorRelay", intakeleftIntakeMotorRelay);
        
        intakerightIntakeMotorRelay = new Relay(1);
        LiveWindow.addActuator("Intake", "rightIntakeMotorRelay", intakerightIntakeMotorRelay);
        
        intaketoteCapturedSwitch = new DigitalInput(8);
        LiveWindow.addSensor("Intake", "toteCapturedSwitch", intaketoteCapturedSwitch);
        
        intakebottomIntakeMotorRelay = new Relay(2);
        LiveWindow.addActuator("Intake", "bottomIntakeMotorRelay", intakebottomIntakeMotorRelay);
        
        latcheslatchReleaseSolenoid = new Solenoid(1, 2);
        LiveWindow.addActuator("Latches", "latchReleaseSolenoid", latcheslatchReleaseSolenoid);
        

    }
}
